// <auto-generated />
using System;
using EgyptionPioneersProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptionPioneersProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124171543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptionPioneersProject.Models.Appointment", b =>
                {
                    b.Property<int>("Ap_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ap_Id"));

                    b.Property<DateTime>("A_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("A_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("A_Time")
                        .HasColumnType("time");

                    b.Property<int>("D_Id")
                        .HasColumnType("int");

                    b.Property<int>("P_Id")
                        .HasColumnType("int");

                    b.HasKey("Ap_Id");

                    b.HasIndex("D_Id");

                    b.HasIndex("P_Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.ChatbotSession", b =>
                {
                    b.Property<int>("Cs_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cs_Id"));

                    b.Property<DateTime>("Cs_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cs_Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dis_Id")
                        .HasColumnType("int");

                    b.Property<int>("P_Id")
                        .HasColumnType("int");

                    b.HasKey("Cs_Id");

                    b.HasIndex("Dis_Id");

                    b.HasIndex("P_Id");

                    b.ToTable("ChatbotSessions");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Disease", b =>
                {
                    b.Property<int>("Dis_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dis_Id"));

                    b.Property<string>("Dis_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dis_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Dis_Severity_Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Dis_Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Disease_Symptom", b =>
                {
                    b.Property<int>("Dis_Id")
                        .HasColumnType("int");

                    b.Property<int>("S_Id")
                        .HasColumnType("int");

                    b.HasKey("Dis_Id", "S_Id");

                    b.HasIndex("S_Id");

                    b.ToTable("Disease_Symptoms");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Disease_Treatment", b =>
                {
                    b.Property<int>("Dis_Id")
                        .HasColumnType("int");

                    b.Property<int>("T_Id")
                        .HasColumnType("int");

                    b.HasKey("Dis_Id", "T_Id");

                    b.HasIndex("T_Id");

                    b.ToTable("Disease_Treatments");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Doctor", b =>
                {
                    b.Property<int>("D_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("D_Id"));

                    b.Property<string>("D_Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("D_Experience")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("D_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("D_Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("D_Working_Hour")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("D_Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Md_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Md_Id"));

                    b.Property<int>("D_Id")
                        .HasColumnType("int");

                    b.Property<int>("Dis_Id")
                        .HasColumnType("int");

                    b.Property<string>("Md_Diagnoses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Md_Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Md_Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_Id")
                        .HasColumnType("int");

                    b.HasKey("Md_Id");

                    b.HasIndex("D_Id");

                    b.HasIndex("Dis_Id");

                    b.HasIndex("P_Id");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Notification", b =>
                {
                    b.Property<int>("N_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N_Id"));

                    b.Property<int?>("D_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("N_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("N_Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("P_Id")
                        .HasColumnType("int");

                    b.HasKey("N_Id");

                    b.HasIndex("D_Id");

                    b.HasIndex("P_Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Order_Product", b =>
                {
                    b.Property<int>("O_Id")
                        .HasColumnType("int");

                    b.Property<int>("Pr_Id")
                        .HasColumnType("int");

                    b.HasKey("O_Id", "Pr_Id");

                    b.HasIndex("Pr_Id");

                    b.ToTable("Order_Products");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Patient", b =>
                {
                    b.Property<int>("P_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_Id"));

                    b.Property<string>("Medical_History")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_Age")
                        .HasColumnType("int");

                    b.Property<string>("P_Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("P_Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("P_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("P_Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skin_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("P_Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Symptom", b =>
                {
                    b.Property<int>("S_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("S_Id"));

                    b.Property<string>("S_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("S_Id");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Treatment", b =>
                {
                    b.Property<int>("T_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("T_Id"));

                    b.Property<string>("T_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("T_Id");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Treatment_Product", b =>
                {
                    b.Property<int>("T_Id")
                        .HasColumnType("int");

                    b.Property<int>("Pr_Id")
                        .HasColumnType("int");

                    b.HasKey("T_Id", "Pr_Id");

                    b.HasIndex("Pr_Id");

                    b.ToTable("Treatment_Products");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("O_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("O_Id"));

                    b.Property<DateTime>("O_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("O_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("O_Total_Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("P_Id")
                        .HasColumnType("int");

                    b.HasKey("O_Id");

                    b.HasIndex("P_Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Pr_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pr_Id"));

                    b.Property<string>("Pr_Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pr_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pr_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Pr_Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Pr_Stock")
                        .HasColumnType("int");

                    b.HasKey("Pr_Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Appointment", b =>
                {
                    b.HasOne("EgyptionPioneersProject.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("D_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptionPioneersProject.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("P_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.ChatbotSession", b =>
                {
                    b.HasOne("EgyptionPioneersProject.Models.Disease", "Disease")
                        .WithMany("ChatbotSessions")
                        .HasForeignKey("Dis_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptionPioneersProject.Models.Patient", "Patient")
                        .WithMany("ChatbotSessions")
                        .HasForeignKey("P_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Disease_Symptom", b =>
                {
                    b.HasOne("EgyptionPioneersProject.Models.Disease", "Disease")
                        .WithMany("DiseaseSymptoms")
                        .HasForeignKey("Dis_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptionPioneersProject.Models.Symptom", "Symptom")
                        .WithMany("DiseaseSymptoms")
                        .HasForeignKey("S_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Disease_Treatment", b =>
                {
                    b.HasOne("EgyptionPioneersProject.Models.Disease", "Disease")
                        .WithMany("DiseaseTreatments")
                        .HasForeignKey("Dis_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptionPioneersProject.Models.Treatment", "Treatment")
                        .WithMany("DiseaseTreatments")
                        .HasForeignKey("T_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.MedicalRecord", b =>
                {
                    b.HasOne("EgyptionPioneersProject.Models.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("D_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptionPioneersProject.Models.Disease", "Disease")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("Dis_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptionPioneersProject.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("P_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Notification", b =>
                {
                    b.HasOne("EgyptionPioneersProject.Models.Doctor", "Doctor")
                        .WithMany("Notifications")
                        .HasForeignKey("D_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EgyptionPioneersProject.Models.Patient", "Patient")
                        .WithMany("Notifications")
                        .HasForeignKey("P_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Order_Product", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("O_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("Pr_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Treatment_Product", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany("TreatmentProducts")
                        .HasForeignKey("Pr_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptionPioneersProject.Models.Treatment", "Treatment")
                        .WithMany("TreatmentProducts")
                        .HasForeignKey("T_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("EgyptionPioneersProject.Models.Patient", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("P_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Disease", b =>
                {
                    b.Navigation("ChatbotSessions");

                    b.Navigation("DiseaseSymptoms");

                    b.Navigation("DiseaseTreatments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ChatbotSessions");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Symptom", b =>
                {
                    b.Navigation("DiseaseSymptoms");
                });

            modelBuilder.Entity("EgyptionPioneersProject.Models.Treatment", b =>
                {
                    b.Navigation("DiseaseTreatments");

                    b.Navigation("TreatmentProducts");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("TreatmentProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
